"""
Django settings for bulk_email_system project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_a280ne&yut5e4sthq$13669vpshcc=z=xn9_z^si@##qf+7x0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'campaigns',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'bulk_email_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "campaigns.context_processors.quarterly_planned_counts",

            ],
        },
    },
]

WSGI_APPLICATION = 'bulk_email_system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery - simple dev config (no external broker)
CELERY_BROKER_URL = "memory://"          # in-memory broker
CELERY_RESULT_BACKEND = "cache+memory://"  # in-memory backend
CELERY_TASK_ALWAYS_EAGER = True          # run tasks immediately, no worker needed
CELERY_TASK_EAGER_PROPAGATES = True      # errors bubble up normally in dev

# ---------------------------------------
# EMAIL CONFIGURATION (Gmail)
# ---------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "dharshikapriya09@gmail.com"
EMAIL_HOST_PASSWORD = "dkmk heku ycrv lrvk"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMIN_REPORT_EMAIL = "dharshikapriya09@gmail.com"

import os

IMAP_HOST = "imap.gmail.com"
IMAP_PORT = 993
IMAP_USE_SSL = True

# Use the SAME account that sends mails, or a dedicated bounce inbox
IMAP_USERNAME = os.getenv("IMAP_USERNAME", "dharshikapriya09@gmail.com")
IMAP_PASSWORD = os.getenv("IMAP_PASSWORD", "dkmk heku ycrv lrvk")

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "process-scheduled-campaigns-every-minute": {
        "task": "campaigns.tasks.process_scheduled_campaigns",
        "schedule": 60.0,  # every 60 seconds
    },

    "process-all-bounces-every-5-mins": {
        "task": "campaigns.tasks.process_all_bounces",
        "schedule": 300.0,  # every 5 minutes
    },

}

CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = False




