# Generated by Django 5.2.8 on 2025-11-15 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignrecipient',
            name='campaigns_c_campaig_1a8cf7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.recipient'),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
