# Generated by Django 5.2.8 on 2025-11-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
