# Generated by Django 5.2.8 on 2025-11-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_recipientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Select which recipient groups this campaign should be sent to.', related_name='campaigns', to='campaigns.recipientgroup'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='campaigns.recipientgroup'),
        ),
    ]
